### ISSUE TITLE
 https 请求服务，导致不能正确的跳转

### ISSUE THREAD

**Issue by hx0806** [cskefu/cskefu#1005]
![image](https://github.com/cskefu/cskefu/assets/59081811/dd083aae-5b87-474d-b283-d832e7b7efa2)
nginx 配置了SSL  http 转 https 后   添加、删除坐席 失败
报错：
Mixed Content: The page at 'https://chat.gjjyun.cn/' was loaded over HTTPS, but requested an insecure frame 'http://chat.gjjyun.cn/admin/organ/index.html?organ=2c9680858dd4fc95018dd531475500da&msg=not_allow_remove_user&models=cca&models=chatbot&models=messenger&models=report&models=contacts&schema=http&port=80&hostname=chat.gjjyun.cn&subtype=role&maintype=admin&typename=methodName&webimport=443&sessionid=B3A5FC251A748603077EC375276A243D&ip=172.25.0.6&userExpTelemetry=on'. This request has been blocked; the content must be served over HTTPS.

**Comment by hailiang-wang** [comment]
该问题已经解决，使用最新的代码。
参考 https://github.com/cskefu/cskefu/issues/1004

**Comment by hailiang-wang** [comment]
创建工单时，请填写代码版本，方法：

## 方法一

进入代码库并执行 `git rev-parse HEAD`

## 方法二

登录系统，在右上角菜单选择  【关于产品】

![screenshot_20240315075832](https://github.com/cskefu/cskefu/assets/3538629/900d8898-92bd-463b-8a95-84f51b07e620)

获得截图，复制字符串 build.

![screenshot_20240315075922](https://github.com/cskefu/cskefu/assets/3538629/0e6e67eb-35fb-475c-81c5-b55a243d42ac)

**Comment by hx0806** [comment]
![image](https://github.com/cskefu/cskefu/assets/59081811/0995533a-6b07-4def-a1d3-2cb69f326cac)

**Comment by hailiang-wang** [comment]
使用 develop 分支最新的代码。

**Comment by hx0806** [comment]
可以在我是用的这版代码中修改吗？    这个问题是调整代码还是配置文件？

**Comment by hailiang-wang** [comment]
这个您通过和最新代码的比对，自己决定怎么做。
thanks。

**Comment by hx0806** [comment]
好的  感谢
