### ISSUE TITLE
无法获得官方API的token

### ISSUE THREAD

**Issue by sqh774-creator** [cskefu/cskefu#1007]
![微信截图_20240321154246](https://github.com/cskefu/cskefu/assets/156745344/8f361895-7ea6-48f5-9473-f1789b1aa935)
官方的RESTful文档里的获得令牌一直是404

**Comment by lecjy** [comment]
![1711114967956](https://github.com/cskefu/cskefu/assets/9280760/4c5d6599-4623-41b0-8b42-c5aa6cd109f4)

"/tokens"在a85a4a33308这次commit时被修改为"/auth/token/bearer"了

https://github.com/cskefu/cskefu/commits/a85a4a33308c487169b75fd8d340c93eaaa618fc/contact-center/app/src/main/java/com/cskefu/cc/controller/auth/ApiAuthBearerController.java
