### ISSUE TITLE
建立连接后无法分配席位，发消息收不到

### ISSUE THREAD

**Issue by wangjian66677** [cskefu/cskefu#1013]
## 描述

![image](https://github.com/cskefu/cskefu/assets/112616551/e5303274-f34f-4cef-90d1-61fbc54b0661)

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by hailiang-wang** [comment]
@wangjian66677 

参考：

https://github.com/cskefu/cskefu/issues/1012

是否是同一个问题？

提供部署方案，代码版本。
Thanks

**Comment by hailiang-wang** [comment]
付费用户春松客服提供远程技术支持。如需远程技术支持，可以将购买证书的手机号发邮件给 info@chatopera.com，邮件标题 【春松客服 issue XXX 证书手机号】，比如 `【春松客服 issue 1012 证书手机号】`。

春松客服证书购买和使用，参考：

https://readthe.gitee.io/cskefu-docs/docs/licenses

感谢支持开源客服系统。

**Comment by wangjian66677** [comment]
docker-compose -f docker-compose.yml up -d  直接启动的。

**Comment by wangjian66677** [comment]
docker-compose -f docker-compose.yml up -d  直接启动的。

**Comment by wangjian66677** [comment]
自己重新打war包的docker镜像，然后使用docker-compose启动，可以解决这个问题。
兄弟们如果直接使用线上的镜像，端口有问题，socket.io连接不上。
附上dockerfile:

FROM chatopera/java:17

##镜像作者
LABEL maintainer=wangjian

##将同级目录target目录下的jar复制到容器内部，命名为app.jar
COPY target/*.war /app.war

##镜像启动命令
ENTRYPOINT ["java","-jar","/app.war"]

**Comment by xiaolei000129** [comment]
我也发现了，但是我把浏览器切换为手机模式就可以使用了

**Comment by lecjy** [comment]
和 [#1012](https://github.com/cskefu/cskefu/issues/1012)是同一个问题
