### ISSUE TITLE
这种发垃圾邮件的项目，都被人挂出来了，还有人用？

### ISSUE THREAD

**Issue by xtay573269555** [cskefu/cskefu#1024]
这种发垃圾邮件的项目，都被人挂出来了，还有人用？

[https://www.v2ex.com/t/970292](https://www.v2ex.com/t/970292)

**Comment by hailiang-wang** [comment]
做好开源客服系统，欢迎使用春松客服上线智能客服~

应用部署:

https://cskefu.github.io/docs/docs/deploy

**Comment by hailiang-wang** [comment]
@xtay573269555 已经被永久拉黑。
怀着积极的心态建设好开源客服系统，是我欢迎的，意图破坏社区和谐，引起无关争论的立即永久拉黑。

春松客服的品质，建立在贡献者辛勤的劳动的基础上，几个臭老鼠想要抹黑春松客服，我第一个站出来和他决斗。
