### ISSUE TITLE
开发环境部署ES报错

### ISSUE THREAD

**Issue by Paul890** [cskefu/cskefu#288]
# 描述

开发环境部署ES报错
![image](https://user-images.githubusercontent.com/3679798/72236209-d0e0ee00-3610-11ea-8781-63b4a205a4b1.png)

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Paul890** [comment]
![VQ_J 5)UV~EGNH(`RAF 107](https://user-images.githubusercontent.com/50387777/72233072-12b56880-3600-11ea-824d-5a55a6d6b458.png)

**Comment by Paul890** [comment]
![图片](https://user-images.githubusercontent.com/50387777/72233150-822b5800-3600-11ea-9af9-e2405b70e8b0.png)

**Comment by caijianfang** [comment]
这个问题怎么解决的？遇到了一样的问题

**Comment by hailiang-wang** [comment]
开发环境搭建，参考文档：

https://docs.chatopera.com/products/cskefu/osc/engineering.html


具体说明您的配置过程，这样才能解答，而不是仅描述现象，感谢！


---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
