### ISSUE TITLE
再次本地搭建失败，不知怎么解决

### ISSUE THREAD

**Issue by Zct-123** [cskefu/cskefu#302]
1.docker-compose.yml文件启动
![image](https://user-images.githubusercontent.com/57829156/75976285-16d17880-5f15-11ea-9f24-9a6cfc7bfd04.png)
2.终端导入idea
![image](https://user-images.githubusercontent.com/57829156/75976323-2ea8fc80-5f15-11ea-8368-8397c817fff6.png)
结果
![image](https://user-images.githubusercontent.com/57829156/75976362-42546300-5f15-11ea-8e0a-6d7d83ff79fa.png)
3.用idea导入项目，并配置application-dev.properties
![image](https://user-images.githubusercontent.com/57829156/75976484-7e87c380-5f15-11ea-80f3-0ea100c2e9ab.png)
4.配置环境
![image](https://user-images.githubusercontent.com/57829156/75976573-a70fbd80-5f15-11ea-872f-0705fa549f17.png)
5.启动报错
ERROR o.s.d.e.r.s.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}] [localhost-startStop-1] 

 ERROR o.s.boot.SpringApplication - Application startup failed [main]

**Comment by Samurais** [comment]
ES的配置错误，需要改为：

```
127.0.0.1:8040
```

而不是
```
127.0.0.1:9300
```

这部分是docker和docker-compose的知识，请认真学习《春松客服大讲堂》里的相关内容。
https://ke.qq.com/course/464050

**Comment by Zct-123** [comment]
![image](https://user-images.githubusercontent.com/57829156/76156152-27f6d100-6131-11ea-9218-465d3daae7d3.png)
es问题解决了，但是这问题怎么解决，启动项找不到main方法

**Comment by Zct-123** [comment]
这个配置我已经成功一次，没有问题了。为啥过段时间再次重启又报错了
![image](https://user-images.githubusercontent.com/57829156/76159858-96eb1e80-615f-11ea-9e6b-1c91c19c3b84.png)
 ERROR o.s.d.e.r.s.AbstractElasticsearchRepository - failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:8040}] [localhost-startStop-1] 

Redis报错与超时
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
