### ISSUE TITLE
升级 bot sdk, 使用知识库优化的新接口

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu#344]
## 概述

升级使用 chatopera sdk 3.0.1

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
现在未全部兼容知识库的多答案和多类型，只支持第一个答案是文本的问答对。
