### ISSUE TITLE
怎么使用现有的中间件呢

### ISSUE THREAD

**Issue by jichoucc** [cskefu/cskefu#501]
## 描述

你好，我们原来的服务有装redis、mysql、es等，请问这个客服系统怎么才能接入原有的中间件，不再新起docker容器
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(CentOS)

## 代码版本

osc

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
请完成开发环境搭建，解决方案在这里有介绍：https://docs.chatopera.com/products/cskefu/osc/engineering.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

最好的方式，使用环境变量，参考：
https://docs.chatopera.com/products/cskefu/osc/engineering.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by jichoucc** [comment]
> 请完成开发环境搭建，解决方案在这里有介绍：https://docs.chatopera.com/products/cskefu/osc/engineering.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
> 
> 最好的方式，使用环境变量，参考： https://docs.chatopera.com/products/cskefu/osc/engineering.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

非常感谢，赞
