### ISSUE TITLE
数据库表

### ISSUE THREAD

**Issue by live-in-the-moment** [cskefu/cskefu#603]
调佣在线客服连接时，是如何将数据插入到 uk_agentUser表 内的？
![image](https://user-images.githubusercontent.com/62800943/153986562-7c301d6b-e225-4e21-8098-f2d7aa46aedb.png)

**Comment by live-in-the-moment** [comment]
用户信息

**Comment by hailiang-wang** [comment]
"@After" 声明，使用 AOP 切面完成。
参考春松客服云大讲堂。


---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by hailiang-wang** [comment]
@live-in-the-moment 关于春松客服使用切面编程的知识点，您可以帮忙写一篇总结文章吗？
在我们的春松客服大讲堂视频和PPT中，有详细的介绍，使用切面编程。


![image](https://user-images.githubusercontent.com/3538629/154487174-a79caea1-dc1f-4b38-a204-322078f9bb73.png)


一起做好开源客服系统，请帮忙增加春松客服的文章，感谢！

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
