### ISSUE TITLE
ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection

### ISSUE THREAD

**Issue by King6880** [cskefu/cskefu#607]
## 描述
部署项目后报这个错误
contact-center_1  | 2022-02-23 11:36:48.227 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-1] 
contact-center_1  | 2022-02-23 11:36:56.882 WARN  c.c.s.t.WebSocketTransport - Unauthorized client with sessionId: 7fabb2fd-1037-4329-be1e-778be81fc27b with ip: /110.191.179.241:2550. Channel closed! [nioEventLoopGroup-3-7] 
contact-center_1  | 2022-02-23 11:36:56.954 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-8] 
contact-center_1  | 2022-02-23 11:36:56.958 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-9] 
contact-center_1  | 2022-02-23 11:36:57.025 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-10] 
contact-center_1  | 2022-02-23 11:37:01.863 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-6] 
contact-center_1  | 2022-02-23 11:37:17.967 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-7] 
contact-center_1  | 2022-02-23 11:37:26.602 ERROR c.c.s.t.PollingTransport - 7fabb2fd-1037-4329-be1e-778be81fc27b is not registered. Closing connection [nioEventLoopGroup-3-5]

## 操作系统
CentOS

## 代码版本
default

**Comment by Aalron** [comment]
我项目在本地启动后，别的人在其他机器上用其他账号登陆后，就会一直出现这个问题，请问这个问题后来是怎么解决的呢？？

**Comment by lecjy** [comment]
从socketIO的源码来看com.corundumstudio.socketio.transport.PollingTransport
```
ClientHead client = this.clientsBox.get(sessionId);
if (client == null) {
    log.error("{} is not registered. Closing connection", sessionId);
    this.sendError(ctx);
}
```
是因于sessionId不存在报错，可能的原因是：某个账户登录系统后，系统重启，客户端使用原来的sessionId通信，后端输出了这个日志

**Comment by Aalron** [comment]
登陆后 ，没有进行过重启系统，就一直会出现这个问题

**Comment by lecjy** [comment]
怎样复现这个问题
