### ISSUE TITLE
启动nginx遇到的问题

### ISSUE THREAD

**Issue by King6880** [cskefu/cskefu#611]
启动项目不会自动启动nginx，并且已经将 .env socket端口修改为80，但是还是只能通过8035端口访问
![image](https://user-images.githubusercontent.com/16409505/156121736-b3ebe03f-22c9-4d05-82a6-6886567c40cd.png)
请问启动nginx是需要单独配置什么吗，还是需要单独启动nginx

**Comment by hailiang-wang** [comment]
参考文章：https://blog.csdn.net/samurais/article/details/105820829

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
