### ISSUE TITLE
在网页端是script标签引入 在微信小程序端怎么使用？

### ISSUE THREAD

**Issue by Lucky-ball-go** [cskefu/cskefu#612]
在网页端是script标签引入 在微信小程序端怎么使用？

**Comment by hailiang-wang** [comment]
您看一下这个项目，https://github.com/chatopera/cskefu-wxapp
使用原生的方式接入。

现在这个项目的文档还不充分，代码也有要优化的地方，欢迎提交 PR。

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
