### ISSUE TITLE
请问favicon.ico这个图片有办法换掉不？

### ISSUE THREAD

**Issue by ghost** [cskefu/cskefu#618]
一直是绿色的图标，想做成自定义的，但没有看到哪里可以换这个图标。

**Comment by hailiang-wang** [comment]
自定义的，可更新源码，参考下面春松客服大讲堂，掌握定制开发技能。

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by hailiang-wang** [comment]
invalid
