### ISSUE TITLE
一定要Java JDK-Amazon Corretto吗？jdk1.8可以不

### ISSUE THREAD

**Issue by MiPeng666** [cskefu/cskefu#619]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
JDK 1.8 有很多的！它只是一个标准！！！


Amazon Corretto 目前是最开放的一个实现，其维护者是 Java 之父。

下载 JDK，https://aws.amazon.com/corretto/?filtered-posts.sort-by=item.additionalFields.createdDate&filtered-posts.sort-order=desc

![image](https://user-images.githubusercontent.com/3538629/159198285-4bc6c305-e830-4ab6-88b4-317f8d980175.png)


---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by hailiang-wang** [comment]
后来您用了哪个 SDK，遇到了什么问题吗？

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

**Comment by MiPeng666** [comment]
用的Java JDK-Amazon Corretto，装上了，还没用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatopera/cskefu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月30日(星期三) 晚上7:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatopera/cskefu] 一定要Java JDK-Amazon Corretto吗？jdk1.8可以不 (Issue #619)





 
后来您用了哪个 SDK，遇到了什么问题吗？
 
祝福与不祝福
 
春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
 对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们所有贡献者基于共赢的信念合作。
 回报方式包括：提交 PR、购买春松客服相关的付费产品和服务等。
 
因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

**Comment by hailiang-wang** [comment]
现在有什么更新吗？可以用的话关闭 Issue。

**Comment by hailiang-wang** [comment]
目前使用 java jdk 17
