### ISSUE TITLE
mac 上运行 gen-idea.sh报错

### ISSUE THREAD

**Issue by kingStrong2022** [cskefu/cskefu#683]
## 描述

运行 './admin/gen-idea.sh' 报错：
<img width="1438" alt="图片" src="https://user-images.githubusercontent.com/101569383/162407543-d727653b-d670-4738-a8e8-4f73680906e8.png">

## 操作系统
macOs monterey
mvn : Apache Maven 3.8.5

## 代码版本
7029aa8f5dd6e663253f6af32eaedf1775d4471f

**Comment by hailiang-wang** [comment]
这个是您的环境的问题，您是不是不熟悉 maven 的使用？
这个是基础知识，我们在春松客服大讲堂中有课程。
您可以参考学习一下！

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

**Comment by kingStrong2022** [comment]
> 这个是您的环境的问题，您是不是不熟悉 maven 的使用？ 这个是基础知识，我们在春松客服大讲堂中有课程。 您可以参考学习一下！
> 
> **春松客服大讲堂**
> 
> https://chatopera.blog.csdn.net/article/details/121599407
> ## 祝福与不祝福
> 
> 春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。 对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。 回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。
> 
> 因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

maven是不太熟，我是直接按照文档弄的。用这个脚本admin/gen-idea.sh也需要熟悉maven使用么？
