### ISSUE TITLE
contact-center:develop 启动不成功

### ISSUE THREAD

**Issue by chenghali** [cskefu/cskefu#696]
![image](https://user-images.githubusercontent.com/45415934/163971509-9ee2e108-bbac-4835-8ff4-d6954740909d.png)
![image](https://user-images.githubusercontent.com/45415934/163972339-2e58ac78-70a2-4ba7-8ab4-7afae30bb0a4.png)
![image](https://user-images.githubusercontent.com/45415934/163972405-8ba393d6-366a-4354-8d2d-9be0da3bb864.png)
![image](https://user-images.githubusercontent.com/45415934/163972854-54205e01-376f-479f-becd-1dda26d56938.png)

之前还是可以的，机器关机后，在开机，服务就启动不正常了，麻烦大佬们帮我看看 这个问题如何解决 数据密码那些都是默认的 都没改过，数据库是可以登陆的。

**Comment by Eleven-M** [comment]
可以尝试把uk_snsaccount表的index 删除

**Comment by xiaobo9** [comment]
是不是改过构建代码啊。第四张图片显示 `docker-entrypoint.sh` 执行的时候，找不到 `java` 。构建的镜像有问题。

**Comment by chenghali** [comment]
> 可以尝试把uk_snsaccount表的index 删除

已经重装解决了 谢谢

**Comment by chenghali** [comment]
> 是不是改过构建代码啊。第四张图片显示 `docker-entrypoint.sh` 执行的时候，找不到 `java` 。构建的镜像有问题。

没有，是机器异常断电关机了，后面就启动不起来了，不过 已经重装解决了 谢谢
