### ISSUE TITLE
com.chatopera.compose4j idea配置项目启动时找不到该类

### ISSUE THREAD

**Issue by l1029765971** [cskefu/cskefu#707]
![LH$VAE) 3_)3)JRMYHJLZLE](https://user-images.githubusercontent.com/81734997/170399466-10e9e634-5e6e-422d-b829-051cb8ad77f0.png)
![5QVY$K2_2GD3I5DG`LYD$7W](https://user-images.githubusercontent.com/81734997/170399482-b1b65a3d-100a-4f08-bf51-2f71d93387cd.png)

![9S{1 K3IB%}`)F1%V82W4_V](https://user-images.githubusercontent.com/81734997/170399523-26909b1c-a4c1-427d-8aaf-917561b8e36d.png)

**Comment by hailiang-wang** [comment]
使用开发环境文章，配置 maven 并安装 依赖

```
mvn install
```

https://docs.cskefu.com/docs/osc/engineering
