### ISSUE TITLE
[微信小程序] 客服发起满意度评价，用户评价完之后，系统不显示评价统计信息

### ISSUE THREAD

**Issue by sdliudapei** [cskefu/cskefu#720]
## 描述

客服发起满意度评价，用户评价完之后，系统不显示评价统计信息
![image](https://user-images.githubusercontent.com/65060483/178421725-7c23ac4f-3954-4780-b774-c7729fee1ebf.png)
![image](https://user-images.githubusercontent.com/65060483/178421778-9e8bd499-59fc-4558-872a-1416b0abf2f8.png)
![image](https://user-images.githubusercontent.com/65060483/178421819-4ffd75ac-836d-4aea-b7b9-0bb997ed6554.png)

## 操作系统

- [x] Windows

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
浏览账号，在右上角进入该技能组的上级组织中。

过滤器也可以选择到该技能组。

**Comment by sdliudapei** [comment]
![image](https://user-images.githubusercontent.com/65060483/178427614-7b1f6b98-540a-4ada-a2d7-b560e0ee41ec.png)
搜索条件 指定到具体的客服人员，还是看不到

**Comment by sdliudapei** [comment]
网页版的聊天测试，可以看到统计信息。
小程序端接入的聊天测试，看不到会话历史和统计等信息，请教一下，是什么原因呢？

**Comment by hailiang-wang** [comment]
使用这个小程序的代码吗？

https://github.com/chatopera/cskefu-wxapp

可能是 BUG，欢迎提交 PR。

参与优化春松客服：

https://github.com/chatopera/cskefu

![image](https://user-images.githubusercontent.com/3538629/178431224-f55ed43f-eb57-454a-8856-4e6d12149d16.png)

**Comment by hailiang-wang** [comment]
春松客服小程序渠道代码：https://github.com/chatopera/cskefu-wxapp

开发者在下面的群里，可进行咨询和实现探讨。

![image](https://user-images.githubusercontent.com/3538629/178431918-690fb71e-8253-44ac-bd73-11e80ccfb45c.png)
