### ISSUE TITLE
Fastjson 反序列化任意代码执行漏洞

### ISSUE THREAD

**Issue by sdliudapei** [cskefu/cskefu#735]
## 概述
项目中在哪配置的fastjson呢？我查看maven版本显示的是1.2.47  这个版本有漏洞，
![image](https://user-images.githubusercontent.com/65060483/185275469-b48c80f1-56b3-4bb6-9f73-5f33679c9215.png)

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by sdliudapei** [comment]
已升级到1.2.83，升级后，对系统有没有影响？？

**Comment by hailiang-wang** [comment]
欢迎提交 PR 到春松客服，我们会进行测试验证。
如何提交代码？参考文档：

https://docs.chatopera.com/products/cskefu/osc/contribution.html

**Comment by sdliudapei** [comment]
![image](https://user-images.githubusercontent.com/65060483/185279734-7e357fd0-ccaf-4b53-9d98-fb62fad3f42d.png)
我没有验证这块，只是部署的时候，系统检测到的问题，提示让修复

**Comment by hailiang-wang** [comment]
那可以认为这个版本更改是合理的，至于产生的影响。
需要在使用/测试中，发现影响。
欢迎提交 PR 到 OSC 分支进行测试。
