### ISSUE TITLE
智能机器人回复阈值怎么设置？

### ISSUE THREAD

**Issue by sdliudapei** [cskefu/cskefu#737]
## 描述

知识库设置如下：
![image](https://user-images.githubusercontent.com/65060483/187161378-4377916f-3b9a-45b1-b2da-a6ae2f1cfccb.png)
回复阈值设置如下：
![image](https://user-images.githubusercontent.com/65060483/187161533-ed7a2faa-4acf-456e-b0f8-1b15f961cd07.png)

聊天见下图：
![image](https://user-images.githubusercontent.com/65060483/187161795-e0fb0cd2-c797-4ef0-a94b-4d25fee97702.png)
![image](https://user-images.githubusercontent.com/65060483/187161872-6e56e76d-cb1b-4158-8033-e9a93119b5f3.png)

怎么设置类似的回复阈值呢？？输入新生儿，输出答案，
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by hailiang-wang** [comment]
1）首先增加知识库语料：比如问题的相似问、近义词词典。
2）使用对话测试页面查看分数：得到你的问题的 score。

![image](https://user-images.githubusercontent.com/3538629/187176426-a8e3728b-eb5e-4465-8bf4-1dff25df20f8.png)

3）在春松客服的环境变量上配置阈值：[文档](https://docs.chatopera.com/products/cskefu/work-chatbot/install.html#%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

![image](https://user-images.githubusercontent.com/3538629/187176637-4ccf6e5d-6d16-4a80-9ea8-6868d4568f4a.png)

虽然在机器人控制台是可以配置阈值的，但是优先级没有春松客服环境变量高，所以在机器人控制台设置界面的阈值配置，对于春松客服集成时，并没有效果。
