### ISSUE TITLE
常见问题作为欢迎语的实现

### ISSUE THREAD

**Issue by abellee** [cskefu/cskefu#743]
请问一下 如何把一个多轮对话的话题设置成欢迎语，
就比如用多轮对话软件 设计一个常见问题，希望用户每次进来就能弹出来固定的几个常见问题
现在已经完成了对话的设计 但是每次打开对话界面的时候 就只会弹一次 再进来就不弹了
可能过一会儿又会弹 没有规律 是我哪里没有设置的原因吗？
谢谢～

**Comment by abellee** [comment]
解决了 在回调方法前面加上 `{keep}` 就行了

**Comment by hailiang-wang** [comment]
KEEP 的使用介绍，参考：

对话状态管理

https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-state.html
