### ISSUE TITLE
小程序嵌套春松客服后，图片问题

### ISSUE THREAD

**Issue by sdliudapei** [cskefu/cskefu#760]
## 描述

小程序嵌套春松客服后，在微信开发者工具里，只能选择照片，而在真机调试里，确有拍照、选择图片。在真机里，选择图片或者拍照后，聊天界面不显示图片，请问，这块怎么调试呢？？

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by sdliudapei** [comment]
![image](https://user-images.githubusercontent.com/65060483/199188583-6833b44b-0a37-4983-9fe2-146111ce6d93.png)
![image](https://user-images.githubusercontent.com/65060483/199188627-82bcbe1f-c12d-4344-bb45-76b0141da07c.png)

**Comment by sdliudapei** [comment]
已解决，前台做了图片压缩处理

**Comment by hailiang-wang** [comment]
是用了这个库？ https://github.com/cskefu/cskefu-wxapp

还是在 https://github.com/cskefu/cskefu 中 HTML 修改？

可以提交到春松客服代码中吗？帮助建立一个 PR， thanks

**Comment by hailiang-wang** [comment]
参考文档： 

https://www.cskefu.com/2022/10/30/how-to-sign-dco-for-pr/

期待您的 PR， 👍
