### ISSUE TITLE
2022-11-06 开发者周例会

### ISSUE THREAD

**Issue by SAMZONG** [cskefu/cskefu#769]
## 会议信息

**周日 10:00UTC+8（中文）（单周）**。[转换为您的时区](https://www.thetimezoneconverter.com/?t=10%3A00&tz=GMT%2B8&)

资源：

- [会议记录和议程](https://www.cskefu.com/category/conferences/) | [Bilibili Video](https://space.bilibili.com/34290698/channel/collectiondetail?sid=817713)
- [会议日历](https://www.feishu.cn/calendar/share?token=e1a022850428d49e1ab84aef69e8ee5c)
- [会议链接](https://vc.feishu.cn/j/400656075)

> 更多会议信息参见： https://github.com/cskefu/community

----

👉👉👉 请在当前 Issue 下引入或留言需要讨论的 Issue&PR&或者话题

**Comment by SAMZONG** [comment]
#768 
#767 
#766 
#765 
#764 
#763 
#762 
#761

**Comment by hailiang-wang** [comment]
Meeting Minutes -

https://www.cskefu.com/2022/11/06/devconf-20221106/
