### ISSUE TITLE
CWE-613: Insufficient Session Expiration

### ISSUE THREAD

**Issue by lujiefsi** [cskefu/cskefu#773]
## 现在行为 
复现：
1 在一个页面中登录用户user1

2 在另一个页面管理员删除user1

3 user1仍然可以继续进行各种操作

## 预期行为
user1被删除后，进行操作应该被要求重新登录，或者禁止任何操作
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 解决方案
用户被删除后，删除与其关联的session
## 代码版本

master(我是从gitee上clone的代码)

**Comment by hailiang-wang** [comment]
duplicated with https://github.com/cskefu/cskefu/issues/781
