### ISSUE TITLE
春松客服提供客服软件支持 允许修改吗？

### ISSUE THREAD

**Issue by almerzht** [cskefu/cskefu#792]
![image](https://user-images.githubusercontent.com/18473867/210720259-3c009852-4726-4d36-a03e-b21ba6c36feb.png)

**Comment by hailiang-wang** [comment]
保留春松客服的声明，可以给我们更多的帮助，进行持续的软件维护。
根据我们的授权，您有很大的自由和灵活，但是从大家的相互促进角度看，您应该尽量的帮助春松客服扩大影响力。
开源软件的优化和更新需要长期的支持，感谢。
