### ISSUE TITLE
云服务知识库调试时SDK返回的score为null

### ISSUE THREAD

**Issue by cnjiangjun** [cskefu/cskefu#793]
![image](https://user-images.githubusercontent.com/14171512/210733600-878d1678-3090-4dd6-bd5f-dee4b8738850.png)

测试了几个问题，几乎只有完整输入问题时才会有score返回（返回为1）

**Comment by hailiang-wang** [comment]
score 为 null 这个情况，是 BUG。因为该值必须在 [0,1]

另外，反馈问题的地址为：
![sceenshoot_20230106091734](https://user-images.githubusercontent.com/3538629/210910151-7b50173d-78a4-4ef5-bc71-a19aadfbcb48.png)


目前该地址指向：https://github.com/chatopera/docs/issues/new/choose

**Comment by hailiang-wang** [comment]
经查找，一个接口出现了问题，现在已经修复。
![sceenshoot_20230106092328](https://user-images.githubusercontent.com/3538629/210910715-bee887eb-4203-4d3e-82c8-175887980f52.png)
