### ISSUE TITLE
cskefu-elasticsearch 一直 Restarting (139)

### ISSUE THREAD

**Issue by renziyou** [cskefu/cskefu#798]
## 描述

cskefu-elasticsearch 一直 Restarting (139)

![image](https://user-images.githubusercontent.com/8150303/217686651-2ede80b8-551a-483c-b3d8-187c9b3513e3.png)

![image](https://user-images.githubusercontent.com/8150303/217686551-ff3cdc87-de00-426f-bb12-496b64d60a2b.png)
![image](https://user-images.githubusercontent.com/8150303/217686592-5d661275-b2cb-4139-ae54-794e76ea1e13.png)
## 操作系统

- [x] Linux CentOS Stream 9
- [ ] Docker version 23.0.0, build e92dd87
- [ ] Docker Compose version v2.15.1

**Comment by hailiang-wang** [comment]
参考部署文档中的资源，操作系统介绍:
https://docs.cskefu.com/docs/deploy

**Comment by hailiang-wang** [comment]
如果没有很多的 OS 资源，比如内存不足 16GB，那么可以修改 ES 配置：

* 增加环境变量到文件：https://github.com/cskefu/cskefu/blob/master/docker-compose.yml#L104
* 增加环境变量，修改 JVM 参数：`ES_JAVA_OPTS="-Xms2g -Xmx2g"`, 参考文档 https://www.elastic.co/guide/en/elasticsearch/reference/7.17/advanced-configuration.html ，春松客服 v7 只支持 ES 2.4 版本，不支持更高版本，使用环境变量配置 JVM 参数需要测试。

**Comment by renziyou** [comment]
> 如果没有很多的 OS 资源，比如内存不足 16GB，那么可以修改 ES 配置：
> 
> * 增加环境变量到文件：https://github.com/cskefu/cskefu/blob/master/docker-compose.yml#L104
> * 增加环境变量，修改 JVM 参数：`ES_JAVA_OPTS="-Xms2g -Xmx2g"`, 参考文档 https://www.elastic.co/guide/en/elasticsearch/reference/7.17/advanced-configuration.html ，春松客服 v7 只支持 ES 2.4 版本，不支持更高版本，使用环境变量配置 JVM 参数需要测试。


OS资源是 16核  32G内存的 100G 硬盘空间
![Uploading image.png…]()

**Comment by hailiang-wang** [comment]
如果资源足够，那么就是软件兼容性问题。
春松客服研发测试使用 Ubuntu 16.04 或以上版本。
建议使用 Ubuntu。

**Comment by renziyou** [comment]
> 如果资源足够，那么就是软件兼容性问题。 春松客服研发测试使用 Ubuntu 16.04 或以上版本。 建议使用 Ubuntu。

好的，感谢

**Comment by mougua** [comment]
我在 centos 7.9，Docker version 23.0.1, build a5ee5b1，Docker Compose version v2.17.0-rc.1 下也是不断重启。查看`docker-compose logs`发现是有对访问`/usr/share/elasticsearch/config/scripts`的`access deny`报错，但进去容器后发现权限是没问题的（owner确实是elasticsearch用户），很奇怪。

目前找不到具体原因，但验证过两个可行的解决方法：
1. `docker-compose.yml` 注释掉 `./database/elasticsearch/config:/usr/share/elasticsearch/config`的映射，暂时不知道有什么副作用
2. 换 ubuntu

**Comment by hailiang-wang** [comment]
目前推荐使用 v8，v8 中去掉了 ES.
https://github.com/cskefu/cskefu
