### ISSUE TITLE
服务启动时出现的问题

### ISSUE THREAD

**Issue by Networkscrew** [cskefu/cskefu#800]
![image](https://user-images.githubusercontent.com/127378567/223934962-540f48c5-825b-4c6e-a732-56f94d0a6672.png)

**Comment by dakcom** [comment]
下载镜像就失败了吧，还没到启动阶段

**Comment by hailiang-wang** [comment]
请参考部署文档：https://docs.cskefu.com/docs/deploy

**Comment by hailiang-wang** [comment]
后来解决了吗？
