### ISSUE TITLE
创建新用户，操作失败

### ISSUE THREAD

**Issue by g18201123180** [cskefu/cskefu#805]
创建新用户，操作失败
 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.cskefu.cc.model.UserRole.user -> com.cskefu.cc.model.User; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.cskefu.cc.model.UserRole.user -> com.cskefu.cc.model.User] with root cause [http-nio-8035-exec-5] 

## 操作系统
Ubuntu 20.04

**Comment by hailiang-wang** [comment]
MySQL 数据可以正常访问到吗？
有调整什么代码吗？

**Comment by g18201123180** [comment]
MySQL可以正常访问，修改了MySQL字符集。

**Comment by disconf** [comment]
遇到了相同问题，应该是个bug，不知道有解决没

**Comment by dakcom** [comment]
没有修改代码，提交成功。但是手机号重复不提示具体原因，仅仅是提交失败。
