### ISSUE TITLE
言简意赅，更容易获得帮助，比如问题简述及 root cause 日志语句

### ISSUE THREAD

**Issue by ixzzzz** [cskefu/cskefu#809]
## centos7.9

- [ ] macOS or Mac OSX
- [ ] Windows
- [ √ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本
服务器没到周二会死机，排除不了问题，有没有每周执行一次的代码之类的

**Comment by hailiang-wang** [comment]
没有。

建议使用 linux atop 工具检查什么进程占用资源过高导致死机。
https://haydenjames.io/use-atop-linux-server-performance-analysis/
