### ISSUE TITLE
系统默认的百度的访问统计建议默认为https

### ISSUE THREAD

**Issue by dakcom** [cskefu/cskefu#816]
## 现在行为

百度默认为：
http://api.map.baidu.com/api?v=2.0&ak=00907f112228b2b91e****
建议改为https

这个建议为https，否则因为https混合http，浏览器默认拦截了。

## 操作系统
Ubuntu  20.04

## 代码版本
春松客服® Release: 7.0.0-SNAPSHOT

Build: 20220913.113713.[5efb35b](https://github.com/cskefu/cskefu/commit/5efb35b)

**Comment by hailiang-wang** [comment]
很好的反馈！
您能顺便提交一个 PR 吗？我们很乐意合并该项改进。
