### ISSUE TITLE
外网访问客服测试窗口用不了

### ISSUE THREAD

**Issue by kely33** [cskefu/cskefu#824]
![ee170dda382c6749c1244141df32100](https://github.com/cskefu/cskefu/assets/134681303/53bcf8aa-2eba-4973-8fe9-3cd43bceac69)
![image](https://github.com/cskefu/cskefu/assets/134681303/6209d70d-4f8a-42c4-9b72-9e3d7215e8d3)
![image](https://github.com/cskefu/cskefu/assets/134681303/cab9be26-38fe-427f-90c6-6e55d5ac1161)

在智能机器人绑定了网站渠道的前提下，
本地域名访问可以正常聊天，但是换成外网的域名后，发送的信息都看不到，请问这是什么原因？

**Comment by hailiang-wang** [comment]
访客在聊天窗口中，无法发送信息？

**Comment by hailiang-wang** [comment]
在这个窗口，使用浏览器调试，得到 console log，其中应该有异常信息。

![screenshot_20230529155554](https://github.com/cskefu/cskefu/assets/3538629/d8cf68f4-1181-4079-9039-ee351fe26af5)

请上传异常信息。

浏览器 console log 查看参考，https://segmentfault.com/a/1190000002511877

**Comment by kely33** [comment]
![image](https://github.com/cskefu/cskefu/assets/134681303/9195f128-30c9-4742-8666-120a97066487)
console log报这个错

是按照以上的文档进行部署的

**Comment by kely33** [comment]
辛苦帮忙排查一下什么原因

**Comment by hailiang-wang** [comment]
websocket 端口配置问题，参考
https://github.com/cskefu/cskefu/issues/589

issues 里相关讨论较多。

**Comment by hailiang-wang** [comment]
@kely33 这个问题解决了吗？后来是怎么解决的。
请补充说明。感谢。如解决请同时关闭工单。

**Comment by kely33** [comment]
谢谢，谢谢！已解决！

解决办法：修改内网穿透里的端口映射
