### ISSUE TITLE
机器人客服名称可以修改吗？在哪里修改？

### ISSUE THREAD

**Issue by kely33** [cskefu/cskefu#825]
我看了chatOpera后台，没找到修改名称的路径

**Comment by hailiang-wang** [comment]
Chatopera 云服务中创建机器人时指定，创建后不能修改。

![screenshot_20230531144009](https://github.com/cskefu/cskefu/assets/3538629/ccc37d8f-da36-456f-840d-bec115c749d9)

**Comment by kely33** [comment]
那请问我新建了一个机器人客服2，我将机器人客服1知识库导出的问题导入到机器人客服2中，机器人客服1设置好的阈值可以连同导过来机器人客服2中来吗

**Comment by kely33** [comment]
还是说直接在设置哪里修改就可以实现？

**Comment by hailiang-wang** [comment]
机器人之间的语料转移，使用 CLI 工具：

* https://docs.chatopera.com/products/chatbot-platform/references/cli.html
* https://docs.chatopera.com/products/chatbot-platform/howto-guides/integration/cli-export-import.html

简单说，就是：

导出：

```
bot dicts -a export -f bot.dicts.json 
bot faq -a export -f bot.faqs.json
bot intents -a export -f bot.intents.json 
bot conversation -a export -f bot.conversations.c66
```

导入：

```
bot dicts -a import -f bot.dicts.json
bot faq -a import -f bot.faqs.json 
bot intents -a import -f bot.intents.json 
bot conversation -a import -f bot.conversations.c66
```

**Comment by kely33** [comment]
可以直接在后台进行导出，导入吗？
如图所示：
![image](https://github.com/cskefu/cskefu/assets/134681303/eaa78538-504a-42cd-a0c1-0853fa7c69db)

**Comment by hailiang-wang** [comment]
后来您有什么变更吗？如有代码调整，欢迎 PR。
