### ISSUE TITLE
存在springboot未授权访问漏洞

### ISSUE THREAD

**Issue by honggu025** [cskefu/cskefu#827]
## 概述
Docker部署，最近被扫描出存在“springboot未授权访问漏洞”，前台可通过访问http://xxxx/actuator获取系统信息
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [√] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by honggu025** [comment]
在nginx中配置
`location ~ .*actuator.* {
    deny all;
}`
可屏蔽外界的访问，但不能从根本上解决问题。

**Comment by hailiang-wang** [comment]
这个之前有所考虑：

1）该 path 是给系统运维监控服务使用，actuator 的服务管理接口已经禁用，比如启停服务；
2）该 path 应在反向代理服务中处理，比如屏蔽，见模板：

https://github.com/cskefu/cskefu/blob/master/nginx/templates/ssl.conf

**Comment by hailiang-wang** [comment]
因为上述的考量，该问题不属于漏洞。
感谢您的反馈，如有风险，欢迎提供更多信息。
