### ISSUE TITLE
智能机器人千人千面问答

### ISSUE THREAD

**Issue by chen759330** [cskefu/cskefu#828]
你们的智能机器人怎么实现千人千面的问答题，比如我给客户A打了一个A标签，那么客户A进来，我就给客户A推送A类产品相关问题，如果是客户B进来，我就给客户B推送B类产品相关问题。如果我要实现，需要怎么做，具体要注意哪些东西

**Comment by hailiang-wang** [comment]
这样的问答可以借助多轮对话设计器：每个回复通过函数返回，在函数中识别用户画像，根据用户画像返回。

首先，您看懂下面的介绍需要您先完成入门教程：https://docs.chatopera.com/products/chatbot-platform/tutorials/index.html


## 一个简单的例子

```
// 脚本

+ __faq_hot_list
- {keep} ^get_greetings()

// 函数
// 问候语中关联常见问题
exports.get_greetings = async function() {
    debug("this.user.id %s", this.user.id)


    if (this.user.id == "superadmin") {
        return {
            text: "你好，超级用户"
        };
    } else {

        return {
            text: "机器人可以解答或提供的服务",
            params: [{
                label: "1. 海口有几个机场",
                type: "qlist",
                text: "海口有几个机场"
            }]
        };
    }
}
```

这里很重要的，就是在函数中，使用 `this.user` 和 `this.message` 等内置信息，参考内置函数库：https://docs.chatopera.com/products/chatbot-platform/references/func-builtin/index.html

高级应用，比如通过 HTTP 请求与业务系统集成，比如根据 user id 获得标签等信息：使用内置函数库的 http。


`http` 的使用: https://docs.chatopera.com/products/chatbot-platform/references/func-builtin/basics.html#http
