### ISSUE TITLE
知识库Excel文件导入时，最后一层分类出现多个，不能统一为一个子分类

### ISSUE THREAD

**Issue by kely33** [cskefu/cskefu#829]
![image](https://github.com/cskefu/cskefu/assets/134681303/7b975e30-3821-4497-9abb-09c9dd289fbf)
![image](https://github.com/cskefu/cskefu/assets/134681303/f1364ff3-6508-42bc-9654-4c7e9492653e)
我希望能实现的效果是，“销售相关”这一子分类下的问题可以统一在该子分类上，而不是一个“销售相关”的问题导入，就会给我新增一个“销售相关”的子分类。
请问这种问题如何解决？是我导入的excel文件中的“分类”列下的格式编辑错了吗？

**Comment by hailiang-wang** [comment]
该问题为 Chatopera 云服务 BUG。预计本周解决。

**Comment by hailiang-wang** [comment]
在 bot.chatopera.com 上遇到的问题，请您反馈至 - 
https://github.com/chatopera/docs/issues

https://github.com/chatopera/docs/issues 集中了机器人平台相关问题，在这里您可以看到更多历史记录和常见问题。

感谢。

@kely33

**Comment by hailiang-wang** [comment]
> 了解了！ 另外希望bug解决完之后，可以通知一下我 谢谢谢谢！！

现在服务已经升级了，解决了这个问题。
感谢您的反馈。
