### ISSUE TITLE
spring boot 框架升级到更新版本, 2.x 或 3.x

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu#833]
## 概述

目前春松客服 v8 使用的 springboot 框架为 1.5.x，需要升级 springboot 框架至较新版本：

2.x 或 3.x

**Comment by hailiang-wang** [comment]
历史讨论：

https://github.com/cskefu/cskefu/issues/623

https://github.com/cskefu/cskefu/issues/317

**Comment by hailiang-wang** [comment]
By @lecjy: SpringBoot3分支已推送，SpringBoot升级到3.1.0，因Druid官方未提供正式的SpringBoot3对应的Druid数据源，因此删除了Druid，使用SpringBoot默认的Hikari数据源

**Comment by hailiang-wang** [comment]
在测试中，发现页面响应速度明显提升，使用 spring boot 3 好处明显。

**Comment by lecjy** [comment]
Druid的SpringBoot3版本https://github.com/alibaba/druid/tree/master/druid-spring-boot-3-starter，对应的
1.2.19的版本依赖在cskefu\contact-center\root\pom.xml中被注释起来了

**Comment by lecjy** [comment]
spring-pug4j升级到3.0.0，与ug4j相关的代码目前没有任何改动

**Comment by hailiang-wang** [comment]
> Druid的SpringBoot3版本[https://github.com/alibaba/druid/tree/master/druid-spring-boot-3-starter，对应的](https://github.com/alibaba/druid/tree/master/druid-spring-boot-3-starter%EF%BC%8C%E5%AF%B9%E5%BA%94%E7%9A%84) 1.2.19的版本依赖在cskefu\contact-center\root\pom.xml中被注释起来了

好的，可以去掉，Druid 使用上刚刚遇到不稳定的问题。
https://github.com/cskefu/cskefu/issues/835

**Comment by lecjy** [comment]
启用csrf后无法登录，后台提示Invalid CSRF token found for ...，流浏览器控制台提示Refused to display 'http://...' in a frame because it set 'X-Frame-Options' to 'DENY，WebSecurityConfig类中对应代码更改为
.csrf().disable().headers().frameOptions().sameOrigin()
//                .addFilterAfter(csrfHeaderFilter(), BasicAuthenticationFilter.class)        // TODO lecjy

**Comment by hailiang-wang** [comment]
Csrf 问题可以修改，保留下面这行。

否则网页渠道的聊天控件加载不出来。

![screenshot_20230622174520](https://github.com/cskefu/cskefu/assets/3538629/21f32b04-55c5-4bc4-b882-c2a39f0d18e6)

**Comment by xuepuhao** [comment]
大哥，你springboot和jdk版本能统一一下吗？版本对应不上啊

**Comment by hailiang-wang** [comment]
> 大哥，你springboot和jdk版本能统一一下吗？版本对应不上啊

请说明您使用的代码分支，文档链接等，感谢。

**Comment by xuepuhao** [comment]
https://github.com/cskefu/cskefu.git

**Comment by xuepuhao** [comment]
> > 大哥，你springboot和jdk版本能统一一下吗？版本对应不上啊
> 
> 请说明您使用的代码分支，文档链接等，感谢。

![image](https://github.com/cskefu/cskefu/assets/32286268/3a59baff-d21c-4585-9731-8475e7b385f5)
