### ISSUE TITLE
root/pom.xml 指定 java 版本号与文档不符

### ISSUE THREAD

**Issue by Kaifuny** [cskefu/cskefu#844]
## 现在行为
![image](https://github.com/cskefu/cskefu/assets/16386583/a858b096-2dc3-4a03-91ca-365253856574)

## 预期行为

与开发文档保持一致

## 解决方案

是否确定 开发环境 java 版本 和 maven 版本变化

**Comment by Kaifuny** [comment]
当前 VSCode 的 Java 核心依赖插件（Language Support for Java(TM) by Red Hat）版本的最低要求已经变成 jdk17。

**Comment by hailiang-wang** [comment]
文档中心已经更新描述，使用 jdk 17
https://github.com/cskefu/cskefu-docs/commit/ed9161308d7368c25eb7241c347a4dceceff6823

**Comment by Kaifuny** [comment]
@hailiang-wang 新问题

![image](https://github.com/cskefu/cskefu/assets/16386583/27cfa66c-930a-4fe7-a5bd-2ab2ffe47139)

使用 jdk17 之后，看到控制台输出确认 是 dev 模式，但是没有正确读取 application-dev.properties 内的配置信息

**Comment by hailiang-wang** [comment]
你遇到的问题是使用 VSCode 的开发环境上存在的问题吗？
application-dev.properties 的文件路径是什么？
因为我没有使用 VSCode 开发春松客服，春松客服也是标准的 springboot 应用，建议搜索一下 springboot3 的应用在 vscode 中是如何配置 dev profile 的。

**Comment by hailiang-wang** [comment]
文档中心更可能是旧了，文档中心往往落后于代码的更新。
此处完成了文档的更新，可以关闭。
如遇到新的问题，应新建立 issue 维护。
