### ISSUE TITLE
无法正确获取 application-dev.properties 配置信息

### ISSUE THREAD

**Issue by Kaifuny** [cskefu/cskefu#845]
## 描述
![image](https://github.com/cskefu/cskefu/assets/16386583/1794e2e9-b6a9-4258-ab8a-39cfbcad2969)

启动时，系统正确识别环境。但是无法正确读取 application-dev.properties 的配置参数。application-dev.properties 与 application.properties 在同一个路径下。

## 功能

开发环境配置

## 操作系统

- [x] macOS or Mac OSX 
- [x] VSCode

## VSCode 配置方式
1. 安装 Extension Pack for Java 的插件接个（IntellCode可以忽略不安装）
2. 在项目根目录 添加 .vscode 目录，创建以下两个文件
  * settings.json
  ```json
  {
    "java.compile.nullAnalysis.mode": "automatic",
    "java.jdt.ls.java.home": "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home",// 指定本地 java 版本路径 （注意：这里的路径是 java.home 的路径，不是 bin 的路径）
    "java.configuration.runtimes": [
      {
        "name": "JavaSE-17",
        "path": "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home", // 指定本地 java 版本路径 （注意：这里的路径是 java.home 的路径，不是 bin 的路径）
        "default": true
      }
    ],
    "java.dependency.packagePresentation": "hierarchical",
    "java.dependency.syncWithFolderExplorer": false,
    "java.project.explorer.showNonJavaResources": true
  }
  ```
  * launch.json
  ```json
  {
    "version": "0.2.0",
    "configurations": [
      {
        "type": "java",
        "name": "<contact-center>",
        "request": "launch",
        "mainClass": "com.cskefu.cc.Application", // 指定入口文件
        "projectName": "contact-center",
        "vmArgs": [
          "-Dspring.profiles.active=dev" // 指定 profiles 的对应环境
        ]
      }
    ]
  }
  ```
3. 打开 VSCode 左侧栏，运行与调试栏运行即可

**Comment by hailiang-wang** [comment]
@lecjy 有一个关于 springboot 3 profile 配置的问题，帮忙看看。

**Comment by hailiang-wang** [comment]
有两个参考 -

* 使用另外一个插件启动，可以选择 profile，https://github.com/microsoft/vscode-spring-boot-dashboard/pull/309#issuecomment-1499866377

* 配置 Workspace ？参考 - https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/50

```

{
    "type": "java",
    "name": "Debug (Launch)-PetClinicApplication<spring-petclinic>",
    "request": "launch",
    "cwd": "${workspaceFolder}",
    "console": "internalConsole",
    "stopOnEntry": false,
    "mainClass": "org.springframework.samples.petclinic.PetClinicApplication",
    "projectName": "spring-petclinic",
    "args": "--spring.profiles.active=profile1,profile2",     // <-- Choice 1. via commandline  args
    "vmArgs": "-Dspring.profiles.active=profile1,profile2"  // <-- Choice 2.  via a java system property
}

```

**Comment by Kaifuny** [comment]
@hailiang-wang @lecjy 
![image](https://github.com/cskefu/cskefu/assets/16386583/19ac2b2b-ee22-4c76-987f-fd7c1d6572c5)

spring 3 properties 参数有变化

https://www.springcloud.io/post/2022-11/springboot3-upgrade-guide/#gsc.tab=0

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-properties-migrator</artifactId>
    <scope>runtime</scope>
</dependency>

添加这个 迁移后 再删除这个依赖即可

**Comment by Kaifuny** [comment]
文档部分需要检查下了

**Comment by hailiang-wang** [comment]
配置参数已经变更了，参考 https://docs.cskefu.com 是昨天提交的吧？
这个问题就是导致 active profile 没有生效的原因吗？

我在本地没有使用 springboot properties migrator 也可以正常运行，所以，从少一点依赖的角度，还是不添加好，直接在 properties 文件中使用 springboot 3 要求的名称和格式。

@Kaifuny

**Comment by Kaifuny** [comment]
这个依赖是用来迁移 spring 3检查用的 就用一次，用完删了就可以了。文档已经改好。

**Comment by hailiang-wang** [comment]
@Kaifuny 这个问题已经解决了吗？
