### ISSUE TITLE
客户端打开页面报错

### ISSUE THREAD

**Issue by xuepuhao** [cskefu/cskefu#847]
演示客户端没有出现在线客服按钮，而且报错！
![image](https://github.com/cskefu/cskefu/assets/32286268/e75fb54f-bff2-4c62-bb65-afa8d82701c8)

**Comment by hailiang-wang** [comment]
该问题曾出现过，但是最新的代码已经解决。
请提供使用的代码的版本。

**Comment by hailiang-wang** [comment]
Fixed with https://github.com/cskefu/cskefu/blob/b4bf2698e038a0e253127d0fd2e7e5ca25ceca56/contact-center/app/src/main/java/com/cskefu/cc/config/WebSecurityConfig.java#L51
