### ISSUE TITLE
升级 Spring Boot 3.0 时所有 getReferenceById 报错

### ISSUE THREAD

**Issue by stackfing** [cskefu/cskefu#850]
## 现在行为
所有 getReferenceById 查询到空数据时直接抛异常，很多代码都是基于这个返回值做判空
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by lecjy** [comment]
@hailiang-wang 以前的代码中没有用过getReferenceById这个方法吧

**Comment by stackfing** [comment]
> @hailiang-wang 以前的代码中没有用过getReferenceById这个方法吧

是在 v8 版本的时候出现的，看到是升级 v8 的过程中批量替换了 findById 方法为 getReferenceById

**Comment by hailiang-wang** [comment]
v8 中使用的，重构了数据库表的原因。
`getReferenceById` 的 BUG @lecjy 帮忙看一下吧。

**Comment by lecjy** [comment]
@hailiang-wang 已提交到issue-850

**Comment by zhangchanglong** [comment]
map.addAttribute("entCustomer", accountRes.findById(id)).orElse(null);
修改后的代码，这里编译报错Cannot resolve method 'orElse' in 'ModelMap'，
应该是
map.addAttribute("entCustomer", accountRes.findById(id).orElse(null)）;

很多类似的地方

**Comment by lecjy** [comment]
@zhangchanglong [426a5fd](https://github.com/cskefu/cskefu/commit/426a5fde68bc609cec4d70a9ce18958878566b0e)
