### ISSUE TITLE
新建智能机器人网站渠道不可选

### ISSUE THREAD

**Issue by KimuraKensi** [cskefu/cskefu#855]
## 现在行为
在已新建网站渠道的情况下，新建智能机器人时无法选择网站渠道，下拉框显示为空。
![机器人添加时无法选择网站渠道](https://github.com/cskefu/cskefu/assets/42505687/604d3622-3a69-4ab4-9c9e-9555407600e6)

## 操作系统
Ubuntu 20.04

**Comment by hailiang-wang** [comment]
有两个可能：

1）没有进入一个技能组的组织机构，需要在右上角切换：假如右上角是【我的企业】就选不了机器人的网页渠道，需要切换到比如【售前座席 A 组】


<img width="290" alt="screenshot_20230630143504" src="https://github.com/cskefu/cskefu/assets/3538629/d8eb4d63-97dd-4079-be1a-654e19073b23">

2）网络延迟，在 v7 版本中，这个 API 接口的初次请求返回数据需要 5s 左右

**Comment by zhangchanglong** [comment]
我初步看了下，下拉框数据 没有正常访问后台接口，而是访问了一个google的地址的 没看明白

**Comment by KimuraKensi** [comment]
@hailiang-wang 尝试切换到【售前座席 A 组】，也试过新建一个带技能组的部门并切换到该部门下仍然都显示空。当前系统是v8.

**Comment by TS-shijun** [comment]
应该是Pug的#{}语言没有成功识别

**Comment by hailiang-wang** [comment]
已经复现，预计下周内解决。

**Comment by hailiang-wang** [comment]
## 原因

语法失效了。

https://pugjs.org/language/attributes.html

![screenshot_20230719174904](https://github.com/cskefu/cskefu/assets/3538629/8b3da1f7-47a1-4d8e-b1cb-093f6ca6e080)


```
Caution
Previous versions of Pug/Jade supported an interpolation syntax such as:

a(href="/#{url}") Link
This syntax is no longer supported. Alternatives are found below. (Check our [migration guide](https://pugjs.org/api/migration-v2.html) for more information on other incompatibilities between Pug v2 and previous versions.)
```

## 解决方案

使用新语法。

https://pugjs.org/api/migration-v2.html


比如：

```
- var url = 'pug-test.html';
a(href='/' + url) Link
```

**Comment by zhangchanglong** [comment]
0720 上午8:40 我试了下 最新演示环境，还是有问题

**Comment by ljzorz** [comment]
那是要怎么办？

**Comment by hailiang-wang** [comment]
> 0720 上午8:40 我试了下 最新演示环境，还是有问题

昨天网络问题，没有更新，现在访问 demo.cskefu.com 了。

![screenshot_20230721095839](https://github.com/cskefu/cskefu/assets/3538629/4f220f31-8cb5-43d0-9337-8eb531fd2344)

**Comment by hailiang-wang** [comment]
@zhangchanglong 

查看demo服务的版本，在右上角进入【关于产品】，

![screenshot_20230721095948](https://github.com/cskefu/cskefu/assets/3538629/d9937f8e-812a-4aa2-9d88-e24fdbbcb3b5)

然后点击 ，
![screenshot_20230721100008](https://github.com/cskefu/cskefu/assets/3538629/87aedcc3-bb49-4e1c-96e2-474f7e73996f)

那么，在这个 commit 合并历史中，先于这个 commit 合并的记录都是包含在这个春松客服服务上的。
https://github.com/cskefu/cskefu/commits/develop

**Comment by hailiang-wang** [comment]
> 那是要怎么办？

该问题已经解决，使用最新的 develop 分支代码。

**Comment by zhangchanglong** [comment]
检查了，好了
