### ISSUE TITLE
想咨询下是否支持微信小程序客服的接入

### ISSUE THREAD

**Issue by eliassama** [cskefu/cskefu#856]
需求是这样的，有三个小程序都开通了微信小程序客服。用户点击后会跳转到小程序客服页面。如下图。
![image](https://github.com/cskefu/cskefu/assets/79587688/109d3628-5bd1-4833-9e5d-09fcefdd136e)

而客服在网页端回复用户需要分别登陆两个小程序的管理后台。如下面两张图所示。

<img width="1366" alt="image" src="https://github.com/cskefu/cskefu/assets/79587688/cf39d5d5-bb91-476a-b004-7955b8d049e5">

<img width="1587" alt="image" src="https://github.com/cskefu/cskefu/assets/79587688/d6bdfbb0-f7e4-4692-8097-514cb65867f1">

这种情况下，怎么把这两个小程序客服接入春松客服？我看着是要填写消息服务器配置，然后接入微信小程序的 客服消息 相关 API 。如下面三张图所示。文档地址是 ：https://developers.weixin.qq.com/miniprogram/introduction/custom.html#%E5%90%8E%E5%8F%B0%E6%8E%A5%E5%85%A5%E6%B6%88%E6%81%AF%E6%9C%8D%E5%8A%A1

<img width="1653" alt="image" src="https://github.com/cskefu/cskefu/assets/79587688/4bd845c2-58c1-4f61-88a2-1aa6dce14ee9">
<img width="1364" alt="image" src="https://github.com/cskefu/cskefu/assets/79587688/1e30d1f9-8aef-486d-a5df-c3791ec69368">
<img width="1486" alt="image" src="https://github.com/cskefu/cskefu/assets/79587688/a2ca7943-5c91-402a-a5de-c6eedb940ca3">

**Comment by eliassama** [comment]
不知道有没有比较好的方法可以解决，总结来说就是：客户使用「微信小程序客服」，而客服直接使用 「春松客服」，来进行双向的沟通。

**Comment by hailiang-wang** [comment]
参考: https://github.com/cskefu/cskefu-wxapp

该程序未经过测试，欢迎提供反馈和 PR。

**Comment by eliassama** [comment]
> 参考: https://github.com/cskefu/cskefu-wxapp
> 
> 该程序未经过测试，欢迎提供反馈和 PR。

好的
