### ISSUE TITLE
统计功能满意度统计、客服坐席访问报错

### ISSUE THREAD

**Issue by stackfing** [cskefu/cskefu#861]
## 现在行为
统计功能满意度统计、客服坐席报错
java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/log4j/Logger [in thread "http-nio-9035-exec-10"]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by lecjy** [comment]
@hailiang-wang 需要你处理好org/apache/log4j/Logger依赖编译后上传chatopera私服，从https://github.com/pentaho/mondrianhttps://github.com/pentaho/mondrian下载源码

**Comment by hailiang-wang** [comment]
好的，但是 mondrian 已经使用 mvnrepo 中心仓库的版本了。

https://github.com/cskefu/cskefu/blob/5b185aa19799a2af8d8b38bc9fce89056c29bbf2/contact-center/root/pom.xml#L356

之后我来看吧。

**Comment by lecjy** [comment]
![1688355114927](https://github.com/cskefu/cskefu/assets/9280760/a8ef3ba9-aaaa-4d25-885f-09ca35f6a5b6)
它来自chatopera私服，其中引用了优客服的代码

**Comment by hailiang-wang** [comment]
原因：https://github.com/pentaho/mondrian/tree/3.7 使用了 log4j v1, 而目前项目中使用了 log4j v2，版本不兼容。

解决方案：引入 Log4j 1.x bridge (log4j-1.2-api)

https://logging.apache.org/log4j/2.x/manual/migration.html



![screenshot_20230719085114](https://github.com/cskefu/cskefu/assets/3538629/1689ded0-4241-47a6-a6ec-400e76278881)
