### ISSUE TITLE
https配好后，所有保存按钮，控制台报错。SocketIO已经正常了。

### ISSUE THREAD

**Issue by fmyseo** [cskefu/cskefu#862]
## 描述
https配好后，页面都访问正常，SocketIO也正常。但是所有的保存按钮，一点控制台就报错。报错的那个http链接，https访问也没问题！求助，这到底什么原因啊

![截图_选择区域_20230703145952](https://github.com/cskefu/cskefu/assets/44190467/5b50cb5f-07b5-40c0-9d33-c8c4f2cc6ff8)
![截图_选择区域_20230703145942](https://github.com/cskefu/cskefu/assets/44190467/5a33cf50-3e68-48e7-8f28-a0f6f065337a)

**Comment by hailiang-wang** [comment]
用的是哪个版本的代码？

**Comment by lecjy** [comment]
参考 #866 默认启用https
