### ISSUE TITLE
优化 HTTPS 代码逻辑，去掉 upload目录下读取证书的逻辑

### ISSUE THREAD

**Issue by hailiang-wang** [cskefu/cskefu#866]
## 概述

by @lecjy , `另外如果没有特情况，可以只接使用https不需要支持http1.1，把从upload目录下读取证书的逻辑去掉`

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by lecjy** [comment]
登录后后台会抛如下异常，InstantMessagingExceptionListener#exceptionCaught在异常时ctx.close()导致wss连接不上，但功能不受影响，异常原因不明
javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)

**Comment by hailiang-wang** [comment]
以前启动服务后，使用：
```
http://localhost:8035/
```
访问，那么以后是：
```
https://localhost:8035/
```

是这样么？我启动后 8035 就看不到服务了。

**Comment by hailiang-wang** [comment]
如果默认使用 
```
https://localhost:8035
```

- [ ] 作为调试开发的地址，需要更新文档中心中的相应描述 @hailiang-wang

**Comment by hailiang-wang** [comment]
在春松客服开发测试的时候，不是应该使用

http://localhost:8035 运行吗？

至于 HTTPS 都是使用反向代理比如，nginx, apache 进行处理？

现在为什么是使用 https://localhost:8035 ?

**Comment by hailiang-wang** [comment]
所谓去掉 https 代码逻辑，就是不在 tomcat 中支持 https 的配置吗？

**Comment by lecjy** [comment]
最终方案为默认使用http协议和8035端口，但可以通过配置文件开启https + wss，也就是说支持https + wss有两种方式，一是使用反向代理，在客户浏览器和代理层之间配置，二是cskefu自身支持(借助SpringBoot自动配置功能)通过配置开启https + wss()，这种情况下使用的内置SpringBoot内置的Tomcat。如果使用外部Tomcat就搭配第一种方式
