### ISSUE TITLE
话术小助手下载地址？

### ISSUE THREAD

**Issue by zhangwadan** [cskefu/cskefu#869]
# 描述

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by zhangchanglong** [comment]
![4f7c1be7-6d66-47e0-99b7-5aeea3126784](https://github.com/cskefu/cskefu/assets/3481828/45266dfa-6a97-4ae3-8d0f-1add51ccdd9a)
![0b4c4b65-cb56-4d23-be9a-8da0e67ce2b4](https://github.com/cskefu/cskefu/assets/3481828/89d470af-23c5-4fd3-b509-d97e302cb704)

**Comment by hailiang-wang** [comment]
抱歉，之前的链接失效了，正在寻找备份安装包上传。
另外，您可以搭建 Windows .Net 环境自行构建，小助手代码已经开源：

https://github.com/chatopera/assistant

**Comment by hailiang-wang** [comment]
@zhangwadan 新的下载地址：

https://gitee.com/chatopera/assistant/releases/download/v1.5/Chatopera%E5%B0%8F%E5%8A%A9%E6%89%8B-v1.5.msi
