### ISSUE TITLE
请教一个问题，关于图片上传后的存储位置

### ISSUE THREAD

**Issue by fmyseo** [cskefu/cskefu#870]
## 描述
图片上传后，具体的存储是在什么地方呢？应该怎么删除对应的图片，本地文件的/contact-center/data/upload 里面倒是有对应img的 id，但是删除还是在的。mysql和redis数据库我也找了，没找到有对应特征的！

## 代码版本
用的是v7版本的源码

**Comment by hailiang-wang** [comment]
v7 版本问题目前不解决。thanks.
