### ISSUE TITLE
windows 私服的jar 下载不了 怎么解决

### ISSUE THREAD

**Issue by 18865930870** [cskefu/cskefu#871]
## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by lecjy** [comment]
请附带上日志

**Comment by hailiang-wang** [comment]
根据开发环境搭建的文档

https://cskefu.gitee.io/cskefu-docs/docs/osc/engineering

**Comment by 18865930870** [comment]
好的
