### ISSUE TITLE
if ('#{models.contains("entim")}')  判断错误

### ISSUE THREAD

**Issue by zhangchanglong** [cskefu/cskefu#872]
## 现在行为
微信群 有人反馈，代码里
if ('#{models.contains("entim")}')  多了 单引号，导致 永远true

cskefu\contact-center\app\src\main\resources\templates\apps\index.pug 83行

![1f2bc554-994f-4ab6-8165-643f2d07b398](https://github.com/cskefu/cskefu/assets/3481828/80e3f72f-d309-4a48-942c-934e99e11101)

下面那块 js    if('false')  相当于 有值会执行{}代码

全局搜索了下 有三处 一样的代码

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by hailiang-wang** [comment]
欢迎提交 PR - 

https://www.cskefu.com/2022/10/30/how-to-sign-dco-for-pr/

这个反馈已经给出了具体的修改，那么只需要按照说明提交 PR。
一起做好开源客服系统。
