### ISSUE TITLE
统计功能 -> 客服坐席

### ISSUE THREAD

**Issue by lecjy** [cskefu/cskefu#878]
## 现在行为

有一个问题，统计功能 -> 客服坐席，会报
java.lang.ClassNotFoundException: com.ukefu.util.UKTools

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

v8 develop 分支

**Comment by hailiang-wang** [comment]
使用新的 mondrian jar 

![screenshot_20230720072606](https://github.com/cskefu/cskefu/assets/3538629/3c19ecff-e5fb-4b5d-befa-6c47aa7e75f9)

**Comment by zhangchanglong** [comment]
0720 上午8:40 演示环境  该界面还有问题，报500

**Comment by zhangchanglong** [comment]
检查了，好了
