### ISSUE TITLE
春松客服如何收费，春松许可证，为什么开源

### ISSUE THREAD

**Issue by zhigangonline** [cskefu/cskefu#890]
## 概述
你好我有一个疑问，如果小规摸使用，春松客服会因为协议收费吗？

**Comment by hailiang-wang** [comment]
春松客服收费模式：

1）通过内置的云服务收费，目前包括机器人客服、知识库。相应的收费根据对应的云服务平台收费规则。

2）通过内置的付费资源计费，目前还没有添加，比如座席人数超过指定数将收费。春松客服的该项收费会比现有的 SaaS 和闭源客服系统低。春松客服为用户提供更高的性价比。

以上两种收费模式，是春松客服主要收费模式；其它的收费模式如客服 PaaS 平台和客服系统的插件等，预计明年会落地。

和开源的关系：春松客服的主要基础代码将会以春松许可协议开源，https://www.cskefu.com/2023/06/25/chunsong-public-license-1-0/

为什么开源：通过开源构建更大的客服系统开发者生态，打败闭源和 SaaS 客服系统。
