### ISSUE TITLE
运行项目编译失败

### ISSUE THREAD

**Issue by alayangchao** [cskefu/cskefu#919]
## 描述
运行项目编译时提示：
java: 找不到符号
  符号:   类 ObjectInputFilter
  位置: 类 com.cskefu.cc.basic.MainUtils

## 编译器
idea

## 操作系统

- [x] Windows

**Comment by hailiang-wang** [comment]
开发环境搭建，参考：
https://cskefu.gitee.io/cskefu-docs/docs/osc/engineering
