### ISSUE TITLE
请更新提供详细的API接口和使用方法谢谢，使能通过春松客服管理所有的在线聊天客服，其余第三系统BOT可以通过春松API接口接入

### ISSUE THREAD

**Issue by wumingpc** [cskefu/cskefu#923]
## 概述

请更新提供详细的API接口和使用方法谢谢，使能通过春松客服管理所有的在线聊天客服，其余第三系统BOT可以通过春松API接口接入文字和图片等实时交互

**Comment by hailiang-wang** [comment]
您的标题中描述了多个需求，请分别建立 Issue，感谢。
