### ISSUE TITLE
[SPAM] 请不要向  GitHub 用户发送垃圾邮件 谢谢

### ISSUE THREAD

**Issue by mritd** [cskefu/cskefu#931]
## 概述

请不要向 GitHub 用户发送垃圾邮件, 这种做法会让人感到厌恶

<img width="725" alt="image" src="https://github.com/cskefu/cskefu/assets/13043245/96e2f615-376d-41a6-a883-a74c4c335de1">

**Comment by hailiang-wang** [comment]
如果不希望得到邮件，您在 GitHub Profile 的公开信息中，不要公开邮件。
在开源社区公开邮件的人，我们认为其心态是开放的，您可以：
* 在我们发送的邮件中取消订阅
* 在您的公开信息中，不要展示邮箱
* 在您的公开信息中，表示不希望接收邮件

如果您没有参与开源项目的开放心态，公开邮件地址，这不是浪费我们的热情吗？
收到我们的开源动态给我们做这样一个 Issue，不是浪费我们的热情吗？

**Comment by hailiang-wang** [comment]
@mritd 我们发的邮件不是垃圾邮件，而你也是自己公开的邮箱。

![screenshot_20230901062905](https://github.com/cskefu/cskefu/assets/3538629/cf862d02-7792-46f3-af11-be1e1569a58d)
