### ISSUE TITLE
【事故一】改过自新，同样也是一个励志的故事

### ISSUE THREAD

**Issue by Kaifuny** [cskefu/cskefu#934]
产品经理：Kaifuny，整理及留档纪要
> 当不了正面代表，当个反面典型也没啥不好的

## 事情概述

事情起因是，源自于 #931 的关于收到春松客服通知邮件信息措施不当，加之由于在该 #931 下的回应也欠妥，给 @mritd 用户带来了极大的心理伤害。进而又在 v2ex 下面发帖，[帖子链接](https://v2ex.com/t/969939?p=3) 进一步控诉以及对于欠妥的回应表达了强烈的不满。同样也由于措辞激烈引发了更大的讨论

![image](https://github.com/cskefu/cskefu/assets/16386583/79674a19-adbe-48cc-bc9e-d56fb82f0285)

## 我们的理解

我们能够理解开发者在收到垃圾邮件的愤怒和无奈，这次的确是不仅在手段上亦或是在后续的回应上都有不对的地方。我们后续会杜绝此类事件事件的再次发生，将更符合开发者社区更为认同的方式。

这个情绪我们切实收到了。

## 非情绪化质疑及回应

1. 关于想赚钱的心情，和道德准绳（亦或是准则）高低的质疑
答：很难将两者画一个等号，去进行此高彼低，此低彼高的评价。不见得赚钱了准绳就高，不赚钱准则就低。现在社区还一直处于一个非盈利的阶段，我们也不着急于商业化，因为还有一些疑问需要解决。关于后者来说，人非圣贤也又脑袋一热的时候。在此感谢各位开发者的愤怒和指责，也希望能够更加的非情绪化的指摘

3. 关于公开邮箱的使用
答：关于公开邮箱的使用，我也是通过这样的机会加入到春松客服这个组织下的。我个人选择是多一个机会，虽然垃圾邮件让我也很苦恼，但是我也仍然开放的将邮箱公开，能够看到一些不一样吧。可能我这么说，是不是我的邮箱也会被爆破了？让我也感受一下垃圾邮箱的威力~

作为此次事件的被告方，我们更应该理解开发者的诉求和意愿。这点我们做错了，我们会找到更好的方式来与开发者之间建立联系。也不希望通过这样的方式认识你们，将来的我们。

5. 开源承诺的质疑
答：现在关于春松客服系统的协议，我们是基于 Apache 2.0 的基础之上演化的。也是希望对于未来商业化的可能性至少得给参与者一个交代。我们会承诺代码肯定是开源可审计的前提下，逐步思考开源商业化的可能性。现在这个开源协议既不实际可能也可能有不得体的地方。对于公众的疑问，我们欢迎质疑并尽力告知我们想做的是一件什么事情，而不仅仅只是被动理解下的一种“诡辩般”的解释

7. 对于道德委员会作用的疑问
答：这个可能我的确了解不多，虽然同道德委员会也深入聊过关于将来的幻想与想象。这个我个人理解一种对内审视下，一个必须存在的一个组织下的一个环节。也并不希望因为这次事件项目的参与者，已经使用的人造成心理压力。开诚布公阐明释义也是我们希望的。对于 cskefu 组织此次行为的代表还是 cskefu 组织本身，个人做的事情既要代表，但对外的确也又是一个整体。

9. 关于是否违反《互联网广告管理暂行办法》
以下是广告法适用范围及主体
![image](https://github.com/cskefu/cskefu/assets/16386583/b6bfb3f2-dcb4-4b5d-a0d7-eb945fac73a2)

初衷并不是广而告知之售卖商品和服务，我们是希望通知形式，进而建立和开发者之间的关系，希望能够让开发者能够了解我们，并加入我们共同建设。在此再为我们本身操作方式产生的误导进行道歉。如果已经给你带来了困扰，邮件都有明显的取消订阅的按钮。这个上面帖子里面也可以看到。

## 最后浅浅的呼吁

cskefu 是一个工具，也是一个开源框架下的组织形式，对于开源的信仰我们理解，社区辩论下对与错我们同样在乎。
此次事故我们铭记于此，改过自新，同样也是一个励志的故事。

## 事故回顾个人总结

- 开源组织形式，仍然有很多的不足和欠妥的地方。不论是对于各类渠道回应的麻烦，以及松散组织下如何快速统一回复的机制
- 我本来就是个刺头，所以我能理解刺头，我能够理解 @mritd 这个人的愤怒以及帖子的热度。可能我们希望的是理性讨论，而不是谩骂和指责，当被如此对待骂回去可能又加深了恶性循环。`解释这件事儿永远不能厌烦可能是社区运作的一个基本素质`
- 初衷要在乎，对与错也要在乎。如果不确定，挨一顿骂也挺好的

**Comment by Kaifuny** [comment]
此次事件跟踪留档作为会议纪要，周天也一并讨论下了。在这里挂一礼拜了，如何处理关联 issue 后续处理方案了

**Comment by Kaifuny** [comment]
> 见过丧事喜办的，没见过认错了还把对方叫"刺头"的👍

哈哈哈哈，我以前就经常被我们老板这么说来着，我能怎么办就当他夸我了~总不能我自己抑郁了吧。没有贬义的意思啦，刺头没啥不好的，骂人骂到点上，说明看问题透彻

**Comment by MFWT** [comment]
希望你们能够注意到一件事，『看到用户公布了邮箱地址就投放推广邮件』这件事**本来就不是一件有礼貌且符合GitHub ToS或者别的什么ToS的事情**，直接定性为SPAM是一点问题也没有的，因为SPAM的定义就是『unsolicited messages sent (in bulk) by email』。人是有心的，总不能说『我不想收到SPAM但是可以发发SPAM，哎哟没事啦』之类的话。

另外，[V2EX的那个帖子的#158楼](https://v2ex.com/t/969939?p=2#r_13584581)，这位名叫『罗奇奇』的用户的发言，**不知道你们是怎么看待的**，**是代表了你们社区的意见吗**？从他的话里，字面意义上能看到道歉二字，但是我看不出『真心』悔改的态度，至少这也不是道歉的态度。

我希望你们能进一步作出澄清，毕竟已经发生的事情，再混淆视听的话只会引起更多的争论。

**Comment by Kaifuny** [comment]
> 希望你们能够注意到一件事，『看到用户公布了邮箱地址就投放推广邮件』这件事**本来就不是一件有礼貌且符合GitHub ToS或者别的什么ToS的事情**，直接定性为SPAM是一点问题也没有的，因为SPAM的定义就是『unsolicited messages sent (in bulk) by email』。人是有心的，总不能说『我不想收到SPAM但是可以发发SPAM，哎哟没事啦』之类的话。
> 
> 另外，[V2EX的那个帖子的#158楼](https://v2ex.com/t/969939?p=2#r_13584581)，这位名叫『罗奇奇』的用户的发言，**不知道你们是怎么看待的**，**是代表了你们社区的意见吗**？从他的话里，字面意义上能看到道歉二字，但是我看不出『真心』悔改的态度，至少这也不是道歉的态度。
> 
> 我希望你们能进一步作出澄清，毕竟已经发生的事情，再混淆视听的话只会引起更多的争论。

澄清事情就是放在这里的，帖子也在讨论，对错很清楚没必要澄清。180度鞠躬道歉，也不能解决情绪化的愤怒，以及既定结果。变着花样的做公关博个满堂彩，我自认为我们这个开发者为主的组织这个本事没有。

我能做的记录跟踪，以后关于这个邮件地址推广的事情，我们会以社区接受的方式，而不是去否定推广本身这也并不是你们要的结果。

**Comment by Kaifuny** [comment]
错了就错了，认错就认错了，改正也是后面看表现，欢迎监督，将来挖坟嘛

**Comment by lingoo** [comment]
你们这公关我真的是折服了。。。能在每一次回应都增加黑点。每。一。次。。。
刺头这个，你当老板夸你，so？

**Comment by lxh0508** [comment]
图片中的那几个大字真的很配你们的德行，赞一个

**Comment by Kaifuny** [comment]
> 你们这公关我真的是折服了。。。能在每一次回应都增加黑点。每。一。次。。。 刺头这个，你当老板夸你，so？

这不是个公关，就是个记录~我个人用词罢了，我没觉得有啥贬义的意思。所以我离职了。高情商说法我也说不出来啥。

关于垃圾邮件这个事儿，我们的确真没有这个主观故意去制造和推送这个事情。如果的确带来困扰，如果已经发生请点击取消订阅，如果后续我们接受社区监督

**Comment by zijiwork** [comment]
持续关注 [https://github.com/dnsjia/luban](https://github.com/dnsjia/luban)

**Comment by Kaifuny** [comment]
> 图片中的那几个大字真的很配你们的德行，赞一个

这个事情造成的误解，都来自于双方尖锐且欠妥的表述，都别删就是了。骂过来自然也要骂回去，能有啥结论。都不是啥好词儿，各自都这么觉得。欢迎社区监督

**Comment by Kaifuny** [comment]
> > 我能做的记录跟踪，以后关于这个邮件地址推广的事情，我们会以社区接受的方式，而不是去否定推广本身这也并不是你们要的结果。
> 
> **直接向公开的邮件地址发件进行推广，我是不能接受的**，因为这件事违背了一个很明显的原则，即『我公布这个地址只是为了进行相关事务的通信，而不是接收无关信息』。如果您认为这个观点不对，欢迎您找一个别的官方网站公布出来的邮件地址进行发送，我相信他们『也许』会更喜欢你们的开源项目。
> 
> 在我的观点中，**推广从来都不是问题**，问题是如何合适的推广。站在消费者（或者说使用者）的角度，至少你不能令人反感
> 
> 比如我们讨厌上门推销保险的，讨厌发传单的，但是不会拒绝闲暇时期在街边看到的广告牌，或者电视里的节目间隙播放的广告。究其原因，后两者我可以预料到『我会遇到推广』，甚至碰到有创意的推广我很可能就考虑接受并使用推广目标（还是后者的例子，电视上一群人拧开一瓶汽水，吱一声，大家一起唱歌跳舞，我大概率会想着买来看看味道到底如何）
> 
> 但是前者呢？**『我家为什么要成为你的广告位？』** —— 很显然，邮件地址同理。一个可能比较接近的是，我同时公布了我的qq邮箱，可以轻松看到我的QQ号。如果某位不识好歹的广告商加QQ然后直接发广告的话.....抱歉，借用一下你们作者的原话，『现在已经将您拉黑』

抱歉啊，我没有否认你的观点的意思。我虚心接受，我只是无法你指出的【罗奇奇】相关的评书进行评价，上面我也说明了我的顾虑和原因。

**Comment by Kaifuny** [comment]
> > > 我能做的记录跟踪，以后关于这个邮件地址推广的事情，我们会以社区接受的方式，而不是去否定推广本身这也并不是你们要的结果。
> > 
> > 
> > **直接向公开的邮件地址发件进行推广，我是不能接受的**，因为这件事违背了一个很明显的原则，即『我公布这个地址只是为了进行相关事务的通信，而不是接收无关信息』。如果您认为这个观点不对，欢迎您找一个别的官方网站公布出来的邮件地址进行发送，我相信他们『也许』会更喜欢你们的开源项目。
> > 在我的观点中，**推广从来都不是问题**，问题是如何合适的推广。站在消费者（或者说使用者）的角度，至少你不能令人反感
> > 比如我们讨厌上门推销保险的，讨厌发传单的，但是不会拒绝闲暇时期在街边看到的广告牌，或者电视里的节目间隙播放的广告。究其原因，后两者我可以预料到『我会遇到推广』，甚至碰到有创意的推广我很可能就考虑接受并使用推广目标（还是后者的例子，电视上一群人拧开一瓶汽水，吱一声，大家一起唱歌跳舞，我大概率会想着买来看看味道到底如何）
> > 但是前者呢？**『我家为什么要成为你的广告位？』** —— 很显然，邮件地址同理。一个可能比较接近的是，我同时公布了我的qq邮箱，可以轻松看到我的QQ号。如果某位不识好歹的广告商加QQ然后直接发广告的话.....抱歉，借用一下你们作者的原话，『现在已经将您拉黑』
> 
> 抱歉啊，我没有否认你的观点的意思。我虚心接受，我只是无法你指出的【罗奇奇】相关的评书进行评价，上面我也说明了我的顾虑和原因。我们俩当着人家不在，讨论这个也不合适

**Comment by MFWT** [comment]
> 只是无法你指出的【罗奇奇】相关的评书进行评价，上面我也说明了我的顾虑和原因。我们俩当着人家不在，讨论这个也不合适

这个我也可以理解。毕竟你们是一个社区，而不是一个人，不要也不能单独说了算。只能说是希望有所改进，不要再让大家失望了

**Comment by Kaifuny** [comment]
> > 只是无法你指出的【罗奇奇】相关的评书进行评价，上面我也说明了我的顾虑和原因。我们俩当着人家不在，讨论这个也不合适
> 
> 这个我也可以理解。毕竟你们是一个社区，而不是一个人，不要也不能单独说了算。只能说是希望有所改进，不要再让大家失望了

谢谢理解，我这个人也是个刺头，所以我也不想社区产生一个不必要的误解。也希望大家在讨论时，更多针对于事件本身，社区组织作为代表来进行论述亦或是表达都无妨的。公司形式的组织，诉讼对象就是公司，法人代表也仅代表公司。对此我个人觉得 春松客服 像我上面总结的，组织形式还较为松散，更何况还刚加入。也希望社区讨论的氛围能更包容一些。

**Comment by shoumenchougou** [comment]
> 希望你们能够注意到一件事，『看到用户公布了邮箱地址就投放推广邮件』这件事**本来就不是一件有礼貌且符合GitHub ToS或者别的什么ToS的事情**，直接定性为SPAM是一点问题也没有的，因为SPAM的定义就是『unsolicited messages sent (in bulk) by email』。人是有心的，总不能说『我不想收到SPAM但是可以发发SPAM，哎哟没事啦』之类的话。
> 
> 另外，[V2EX的那个帖子的#158楼](https://v2ex.com/t/969939?p=2#r_13584581)，这位名叫『罗奇奇』的用户的发言，**不知道你们是怎么看待的**，**是代表了你们社区的意见吗**？从他的话里，字面意义上能看到道歉二字，但是我看不出『真心』悔改的态度，至少这也不是道歉的态度。
> 
> 我希望你们能进一步作出澄清，毕竟已经发生的事情，再混淆视听的话只会引起更多的争论。

我表达抱歉，是出于春松客服社区对他人造成了伤害，而我作为其中一员并未能阻止该问题的发生。但我在帖子本身的发言并不代表社区观点。

站在个人立场，我坚定地反对使用群发邮件招募开发者的方法，同样反对使用过分激烈的言辞在社区批评一位用户。

因此我下掉了那篇拉黑的通告，并作出基于个人的承诺：只要我还在春松客服社区，就不会允许再次出现这种 SPAM 推广方法，也不允许社区发布带强烈情绪或攻击性的公告。

社区的问题，理应由社区驱动去解决。关于社区角度的回应，我们会在下一次社区会议上讨论今天发生的一切，并将后续的处理方式公布在该 issue 中

**Comment by hailiang-wang** [comment]
## 做好开源客服系统

诚挚欢迎本贴的互动者和读者加入春松客服开源社区，
https://www.cskefu.com/join-us/

一起做好开源客服系统，
https://github.com/cskefu/cskefu

**Comment by saltfishh** [comment]
> 答：关于公开邮箱的使用，我也是通过这样的机会加入到春松客服这个组织下的。我个人选择是多一个机会，虽然垃圾邮件让我也很苦恼，但是我也仍然开放的将邮箱公开，能够看到一些不一样吧。可能我这么说，是不是我的邮箱也会被爆破了？让我也感受一下垃圾邮箱的威力~

嘴硬是吧

**Comment by saltfishh** [comment]
issue 全是 dislike.
社区做到人见人打也是挺厉害的

**Comment by hailiang-wang** [comment]
我最在意的，是能够一起合作，做好开源客服系统的人。
剩下的人，有很多斯德哥尔摩综合征患者，期待他们能干点什么是不行的，给别人添堵倒是行家里手。

欢迎参加春松客服社区会议，今天下午 2 PM 来聊，共建春松客服开源社区。

请使用[腾讯会议](https://meeting.tencent.com/download/)接入，会议室 ID: 481-700-650

或打开链接：[https://meeting.tencent.com/dw/W8U5pkXWxddR](https://meeting.tencent.com/dw/W8U5pkXWxddR)

会议时间：北京时间 2023 年 09 月 02 日（星期六） 下午 2：00 ~ 4：00

## 入会须知

* **活动仅使用腾讯会议进行，其它活动参与方式请忽略**
* 至少前天 5 分钟进入会议室，最早会议开启前 20 分钟可入会
* 如有问题使用聊天室发送文字，将在问答环节解答

**Comment by Kaifuny** [comment]
> issue 全是 dislike. 社区做到人见人打也是挺厉害的

是啊，也没见你在社区里面人见人爱过

**Comment by Kaifuny** [comment]
![image](https://github.com/cskefu/cskefu/assets/16386583/6c5f7ca0-6e79-4a06-af26-1d18f9c4399d)
试了一下让 ChatGPT 总结了一下，不也没啥问题。为啥会看不懂那么多字儿呢？
