### ISSUE TITLE
使用docker-compose安装后删除再安装，文字链代码地址不正确

### ISSUE THREAD

**Issue by jokerJ88888888** [cskefu/cskefu#950]
## 文字链代码不正确，没有正确读取到ip或者域名

![image](https://github.com/cskefu/cskefu/assets/139462854/b83d81bc-5926-4ec8-9397-708b24ec14f8)

## 操作系统
Linux centos7.x + docker-compose

**Comment by hailiang-wang** [comment]
后来如何解决了？
@jokerJ88888888 

第一次安装后，是否有正确的 IP/域名 地址？
