### ISSUE TITLE
求助！！使用自己构建镜像升级时候，contact-center一直处于重启中

### ISSUE THREAD

**Issue by wz03140** [cskefu/cskefu#953]
## 描述

本地生成镜像
![image](https://github.com/cskefu/cskefu/assets/148753174/5ec4150a-0d6a-448e-9b2f-d4b93165b54a)
修改docker-compose.yml 中 节点为自己加载镜像
![image](https://github.com/cskefu/cskefu/assets/148753174/e1938619-8f24-4d19-acd0-be0e5cdcd1d5)
停止服务后重启
![image](https://github.com/cskefu/cskefu/assets/148753174/67b7b0c2-f62d-4a9a-b2b5-8c0a20bbccbe)
![image](https://github.com/cskefu/cskefu/assets/148753174/5b216e30-d612-4864-9999-c8b110e190a4)
使用自己本地构建镜像升级时候，主程序启动失败，未生成运行日志，需要如何排查问题，求助大佬~~~~帮忙解答

## 操作系统

- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

**Comment by wz03140** [comment]
服务器导入镜像
![image](https://github.com/cskefu/cskefu/assets/148753174/a1cec40e-2342-4caf-8dbf-93a35530243e)

**Comment by lecjy** [comment]
使用的基础镜像里没有/bin/bash这个命令，要么换基础镜像，要么使用其他shell

**Comment by wz03140** [comment]
> 使用的基础镜像里没有/bin/bash这个命令，要么换基础镜像，要么使用其他shell
蟹蟹 蟹蟹  ~
![image](https://github.com/cskefu/cskefu/assets/148753174/b5b2845d-7add-4144-adf5-20d4781b124e)
