### ISSUE TITLE
”坐席对话“页面： 右下角 “关联”联系人，无法关联成功；且在 “选择联系人” 窗口无法搜索到相应的用户，

### ISSUE THREAD

**Issue by diaohongyong** [cskefu/cskefu#956]
## 现在行为
”坐席对话“页面： 右下角 “关联”联系人，无法未成功；且在 “选择联系人” 窗口无法搜索到相应的用户，不知道这块的功能是否已实现或是bug问题导致；

## 操作系统
CentOS

<img width="1242" alt="Screenshot at 10月 30 20-58-40" src="https://github.com/cskefu/cskefu/assets/63226907/acddc7ea-ac35-444c-8d69-6f22069ab89e">
<img width="1224" alt="Screenshot at 10月 30 21-01-44" src="https://github.com/cskefu/cskefu/assets/63226907/36cb4c4f-0dfb-4306-9bc4-6f29d4f6e0ee">
<img width="1117" alt="Screenshot at 10月 30 20-59-27" src="https://github.com/cskefu/cskefu/assets/63226907/15714d9a-c7ac-442b-8694-74d6cf581a3c">
<img width="1274" alt="Screenshot at 10月 30 20-56-58" src="https://github.com/cskefu/cskefu/assets/63226907/75499b06-cf03-4cbc-ad25-23dbb239b6dc">

**Comment by hailiang-wang** [comment]
该功能之前是工作的，可以确定是一个 BUG。


@lecjy 有空先看一下。
