### ISSUE TITLE
春松客服系统中-客服设置-知识库知识-具体作用

### ISSUE THREAD

**Issue by wz03140** [cskefu/cskefu#957]
## 描述
春松客服系统中-客服设置-知识库知识-  目前智能创建标签吗，标签创建后，具体有何作用，该如何使用？

![image](https://github.com/cskefu/cskefu/assets/148753174/2fdf40cc-73f6-4414-9e26-98f6ee93c333)

如果不集成关联智能机器人的话，客服系统本身是否有知识库的相关功能，比如可以录入业务知识，供人工客服自己查询，作为依据提供服务？

## 操作系统
 CentOS

## 代码版本
v8

**Comment by hailiang-wang** [comment]
该知识库标签没有实际用途，是没有机器人客服前的实现。
现在春松客服的知识库只通过【智能对话机器人】管理，见超级管理员的系统管理菜单中。

原因很简单，维护机器人和管理知识库可以真正的为客户业务降本增效。

了解 Chatopera 机器人云服务，定制您的聊天机器人。
https://docs.chatopera.com/

**Comment by wz03140** [comment]
> 该知识库标签没有实际用途，是没有机器人客服前的实现。 现在春松客服的知识库只通过【智能对话机器人】管理，见超级管理员的系统管理菜单中。
> 
> 原因很简单，维护机器人和管理知识库可以真正的为客户业务降本增效。
> 
> 了解 Chatopera 机器人云服务，定制您的聊天机器人。 https://docs.chatopera.com/

好的，谢谢~
![image](https://github.com/cskefu/cskefu/assets/148753174/16fb2e85-394e-4808-94fc-99e775b7cc36)
