### ISSUE TITLE
访客的用户名， 生成规则是怎么样的？

### ISSUE THREAD

**Issue by diaohongyong** [cskefu/cskefu#979]
访客的用户名： 生成规则是怎么样的？ 

同一个访客，第二次登录打开聊天窗口，这个用户名会一直不变么

<img width="1228" alt="Screenshot at 11月 22 16-32-26" src="https://github.com/cskefu/cskefu/assets/63226907/fba9c88e-d7e7-4bcc-a658-6e89bc253e2b">

**Comment by lecjy** [comment]
前端使用fingerprint.js生成了浏览器指纹，作为用户的唯一id，id和用户名一一对应，访客不换浏览器的情况下一般不会变

**Comment by diaohongyong** [comment]
收到， 感谢
