### ISSUE TITLE
客户，联系人两个模块： 添加了相应人员之后，提示添加成功，但始终也不显示所添加成功的记录信息； 未找到原因。

### ISSUE THREAD

**Issue by diaohongyong** [cskefu/cskefu#987]
版本： v8

客户，联系人两个模块： 添加了相应人员之后，提示添加成功，但始终也不显示所添加成功的记录信息； 未找到原因。
聊天窗口右侧："关联联系人"， 无法操作； 无法查询到添加成功的联系人并与之关联。

<img width="1274" alt="Screenshot at 12月 05 16-09-05" src="https://github.com/cskefu/cskefu/assets/63226907/52cf185e-086f-4faf-b2fc-ed85ae15538d">

<img width="1235" alt="Screenshot at 12月 05 16-28-51" src="https://github.com/cskefu/cskefu/assets/63226907/87d89c24-fe01-42fa-a2d2-15da4507efcc">

**Comment by lecjy** [comment]
联系人模块中，不显示添加成功的记录是不是和https://github.com/cskefu/cskefu/issues/956一样的场景，如果是请更新到最新版

**Comment by hailiang-wang** [comment]
合并后，代码是否进入春松客服 docker 镜像，进入哪个镜像？如下。

## develop 分支的 commits

确认代码进入了：

https://github.com/cskefu/cskefu/commits/develop

develop 分支目前 PR 的默认合并分支。

## 在 commit 上查看 CI 任务

如下，有对号的时候代表 CI 执行完成。

![screenshot_20231211093518](https://github.com/cskefu/cskefu/assets/3538629/9ebae52b-c943-4974-b5b4-02bb8555abd3)


## 进入到 docker 镜像的 tag

官方镜像：https://hub.docker.com/r/cskefu/contact-center/tags

![screenshot_20231211094038](https://github.com/cskefu/cskefu/assets/3538629/d2ef3e75-166f-4e41-bf65-529738108a9a)


* 最后一次成功的构建，被标记为 cskefu/contact-center:develop
* 每次构建，都和 commit shortid 关联，比如 `docker pull cskefu/contact-center:0797a90f`, 代表代码就是 https://github.com/cskefu/cskefu/commit/0797a90f
