### ISSUE TITLE
不支持ARM架构系统吗？

### ISSUE THREAD

**Issue by zhoushao2018** [cskefu/cskefu#992]
## 描述
RT 拉取镜像安装包提示这个错误

`! mysql The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                     0.0s 
 ! redis The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                     0.0s 
 ! activemq The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                  0.0s 
 ✔ Container cskefu-contact-center-1                                                                                                                             Started                    0.0s 
 ! contact-center The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requeste`
![image](https://github.com/cskefu/cskefu/assets/63604074/ab38e2c4-9c54-4388-b87d-5903a2272bad)

## 操作系统

Debian 11

**Comment by hailiang-wang** [comment]
我们没有 ARM 架构的环境来构建春松客服 docker 镜像。

**Comment by hailiang-wang** [comment]
这是春松客服构建镜像的 CI 任务，

https://github.com/cskefu/cskefu/blob/develop/.circleci/config.yml

或许是可以在 circleci 中指定 ARM 的 base image 来完成构建，但是这个工作可以您来帮忙做吗？
@zhoushao2018

我们将很乐意合并 PR 来实现 ARM 架构的镜像构建。

**Comment by zhoushao2018** [comment]
> 我们没有 ARM 架构的环境来构建春松客服 docker 镜像。

大佬 我给个ARM服务器给你用一段时间，能搞个镜像吗？

**Comment by zhoushao2018** [comment]
> 这是春松客服构建镜像的 CI 任务，
> 
> https://github.com/cskefu/cskefu/blob/develop/.circleci/config.yml
> 
> 或许是可以在 circleci 中指定 ARM 的 base image 来完成构建，但是这个工作可以您来帮忙做吗？ @zhoushao2018
> 
> 我们将很乐意合并 PR 来实现 ARM 架构的镜像构建。

我不会这些啊，大佬，我有ARM服务器，甲骨文的 2C 16G，你来操作吧，需要服务器信息的话留个邮箱发过去

**Comment by hailiang-wang** [comment]
@zhoushao2018 感谢您的反馈，春松客服团队无法免费的进行这个适配。
