### ISSUE TITLE
部署到云服务器 静态资源加载很慢

### ISSUE THREAD

**Issue by hx0806** [cskefu/cskefu#997]
客服部署到云服务器上后，客服静态资源加载很慢
刷新页面 18秒才把资源加载出来

服务器配置

4核    8G    带宽2M   

[https://github.com/cskefu/cskefu/assets/59081811/2df5e682-cc10-4f2f-b958-73150e20dc8a](url)

**Comment by hx0806** [comment]
![Uploading image.png…]()

**Comment by hx0806** [comment]
![cbec91dad72d12307bdafd7fc432986](https://github.com/cskefu/cskefu/assets/59081811/3d2a568e-c0e3-4877-8105-3df023a45c20)

**Comment by hx0806** [comment]
![cbec91dad72d12307bdafd7fc432986](https://github.com/cskefu/cskefu/assets/59081811/df564184-c959-4e3d-b021-441a4b67276f)

**Comment by hailiang-wang** [comment]
部署依赖的硬件资源，参考：
https://readthe.gitee.io/cskefu-docs/docs/deploy

您部署的是生产环境，8GB 内存太少了。

另外，环境变量配置到 [docker-compose.yml](https://github.com/cskefu/cskefu/blob/develop/docker-compose.yml) 的 contact-center 服务上：

`LOG_LEVEL=WARN`

**Comment by hailiang-wang** [comment]
带宽 2M 这个太小了，非常的不合理，生产环境下，可以选择按量付费，而不是按照固定带宽。
选择按量付费可以有更高的峰值，比如 20MB，而且可能比按照固定带宽更省钱。
